services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      USERNAME: "Lukeewqz"
      PASSWORD: "ILoveYou"
      RAM_SIZE: "7G"
      CPU_CORES: "10"
      DISK_SIZE: "900G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
